eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8090}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
