eureka:
   client:
      healthcheck:
        enabled: true
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
      preferIpAddress: true
      
test:
  value: Hello world
